name: myfirstpipeline

on:
  workflow_dispatch:  #manual trigger
jobs:
  myfirstjob:
   runs-on: ubuntu-latest # agent hai ye
   steps:
     - name: 
       run: echo "hello guys"
  mysecondjob:
   runs-on: windows-latest # agent hai ye
   steps:
     - name: 
       run: write-host "hello guys"
