name: myfirstpipeline
 
on:
  workflow_dispatch:  #manual trigger
# env:
#   MY_NAME: Mona 
jobs:
  myfirstjob:
   # continue-on-error: true
   name: first_job_name
   runs-on: ubuntu-latest # agent hai ye
   steps:
     - name: 
       # run: echo "hello $MY_NAME"
       run: echo "my first devops job at 12 LPA to ${{vars.MY_NAME}}"
  mysecondjob:
   # needs: myfirstjob
   # if: always()
   name: second_job_name
   runs-on: windows-latest # agent hai ye
   steps:
     - name: 
       # run: write-host "hello meri jaan $env:MY_NAME"
       run: echo "meri pahali devops job"
